# Adapted from https://raw.githubusercontent.com/hvr/multi-ghc-travis/master/.travis.yml
env:
 - GHCVER=7.8.2

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update -qq
 # We need gcc 4.8 because the default 4.6 has a bug with MPFR: https://bugs.launchpad.net/ubuntu/+source/gcc-4.6/+bug/968766
 - travis_retry sudo apt-get install -qq gcc-4.8
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy-1.19.3
 - export PATH=/opt/happy/1.19.3/bin:/opt/ghc/$GHCVER/bin:$PATH
 - export CC="gcc-4.8"

install:
 - cabal-1.18 update
 - cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks

script:
 - cabal-1.18 configure --enable-tests --enable-benchmarks -v2
 - cabal-1.18 build
